### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by spekulatius**
Was it just me or was the mysql server missing?

### CODE REVIEW

**Comment by moul** [comment]
That was not just you :)

I think, we tested the image with a remote MySQL server

**Comment by moul** [comment]
Finally, I think mysql-server was a dependency of another package, because we have some scripts that manipulate the local mysql server

With your commit, we are 100% sure to get it installed even if the package dependencies change

**Comment by spekulatius** [comment]
Yeah, could be. As long as its there now :)

**Comment by aimxhaisse** [comment]
It was installed here: https://github.com/scaleway/image-app-lemp/blob/master/patches/usr/local/sbin/oc-init-php-mysql#L16

**Comment by spekulatius** [comment]
yeah, it didn't search further after I realized it isn't installed... So I just added it and open a PR to save others the time to investigate.

**Pull request merged**
